# Generated by Django 4.2.5 on 2023-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_accounting1", "0003_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="entry_set",
            field=models.ManyToManyField(to="warehouse_accounting1.entry"),
        ),
    ]
