# Generated by Django 4.2.5 on 2023-10-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_accounting1", "0004_category_entry_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                ("quantity_on_stock", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="category",
            name="entry_set",
        ),
        migrations.RemoveField(
            model_name="category",
            name="text",
        ),
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(default="Немає назви", max_length=100),
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse_accounting1.category",
            ),
        ),
    ]
