# Generated by Django 4.2.5 on 2023-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_accounting1",
            "0005_item_remove_product_category_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=25),
        ),
    ]
